# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainHedding = QtWidgets.QLabel(self.centralwidget)
        self.MainHedding.setGeometry(QtCore.QRect(87, 40, 126, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MainHedding.setFont(font)
        self.MainHedding.setObjectName("MainHedding")
        self.LoginHedding = QtWidgets.QLabel(self.centralwidget)
        self.LoginHedding.setGeometry(QtCore.QRect(30, 110, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.LoginHedding.setFont(font)
        self.LoginHedding.setObjectName("LoginHedding")
        self.LoginBox = QtWidgets.QLineEdit(self.centralwidget)
        self.LoginBox.setGeometry(QtCore.QRect(85, 140, 130, 30))
        self.LoginBox.setObjectName("LoginBox")
        self.PasswordHedding = QtWidgets.QLabel(self.centralwidget)
        self.PasswordHedding.setGeometry(QtCore.QRect(30, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.PasswordHedding.setFont(font)
        self.PasswordHedding.setObjectName("PasswordHedding")
        self.PasswordBox = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordBox.setGeometry(QtCore.QRect(85, 230, 130, 30))
        self.PasswordBox.setObjectName("PasswordBox")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(105, 300, 90, 30))
        self.SubmitButton.setObjectName("SubmitButton")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainHedding.setText(_translate("MainWindow", "Авторизация"))
        self.LoginHedding.setText(_translate("MainWindow", "Введите Ваш логин:"))
        self.PasswordHedding.setText(_translate("MainWindow", "Введите Ваш пароль:"))
        self.SubmitButton.setText(_translate("MainWindow", "Войти"))
